name: Wiltonfoundry
favicon: null
layout_spectrum: 0.13791643315926194
typography_spectrum: 0.5739088980481029
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4245735036674887
  lightness: 0.9845445714890957
  saturation: 0.4243217147886753
  rhythmicContrast: 0.6956725053023547
purpose: []
